nameOverride: "frontend"
replicaCount: 2
image:
  repository: your-docker-registry/frontend
  tag: "latest"
service:
  port: 80
ingress:
  enabled: true
  hosts:
    - host: myapp.local
      paths:
        - path: /
          pathType: Prefix
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
