apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: encryption-service-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/shaileshp0110/gitops-config.git
    path: charts/microservice
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../../environments/dev/encryption-service/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
